"""
Schemas for portfolio scoring results
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Literal


class SubScore(BaseModel):
    """A sub-score component (0-100) with description."""
    name: str = Field(..., description="Sub-score name: diversification, risk_profile, macro_exposure, asset_quality")
    value: float = Field(..., ge=0, le=100, description="Score value 0-100")
    description: str = Field(..., description="Human-readable explanation of the score")


class Alert(BaseModel):
    """An alert generated by the scoring system."""
    code: str = Field(..., description="Alert code (e.g., HIGH_CONCENTRATION, RISK_PROFILE_MISMATCH)")
    severity: Literal["red", "orange", "green"] = Field(..., description="Alert severity level")
    message: str = Field(..., description="User-facing alert message")
    recommendation: Optional[str] = Field(None, description="Optional recommendation to address the alert")


class PortfolioScoreResult(BaseModel):
    """Complete portfolio scoring result with global score, sub-scores, and alerts."""
    global_score: float = Field(..., ge=0, le=100, description="Weighted global score 0-100")
    sub_scores: List[SubScore] = Field(..., description="Four sub-scores")
    alerts: List[Alert] = Field(default_factory=list, description="Generated alerts")
    
    # Context fields for UI
    investor_profile: str = Field(..., description="Current investor profile (prudent, equilibre, dynamique, agressif)")
    actual_equity_pct: float = Field(..., description="Actual equity allocation percentage")
    concentration_top5: float = Field(..., description="Percentage of portfolio in top 5 positions")
